/**
 * WEB PREVIEW data source. Builds a READ-ONLY `BappDataset` projection from the
 * existing AsyncStorage stores the app already writes to:
 *   - `bapp.history.v1`       (shoes + rounds)
 *   - `bapp.session.v1.<id>`  (per-shoe live session: rounds/predictions/revisions)
 *
 * Destructive writes (Merge apply / Restore) are NOT available on web preview:
 * they throw `WriteUnavailableError` so the UI can label them
 * "Available on native SQLite runtime" instead of faking success.
 *
 * Historical locked predictions are copied VERBATIM (payload = the persisted
 * prediction) — nothing is regenerated by current engine code.
 */
import { storage } from '@/src/utils/storage';
import type { RoundRecord } from '@/src/domain/models/round';
import type { RevisionRecord, ShoeRecord } from '@/src/domain/models/records';
import type { PersistedSession, PredictionEntry } from '@/src/domain/session';
import { StepResult } from '@/src/domain/session';
import type {
  BappDataset,
  LockedPredictionEntryRecord,
  SessionStateRecord,
} from '@/src/domain/backup';
import { WriteUnavailableError, type DataSource } from './data-source';

const HISTORY_KEY = 'bapp.history.v1';
const SESSION_PREFIX = 'bapp.session.v1.';

interface WebHistoryState {
  shoes: ShoeRecord[];
  rounds: Record<string, RoundRecord[]>;
}

// The stores persist `storage.setItem(key, JSON.stringify(state))`, so the
// value returned by storage.getItem is itself a JSON string we must parse.
async function readJson<T>(key: string): Promise<T | null> {
  const raw = await storage.getItem(key, '');
  if (!raw) return null;
  try {
    return JSON.parse(raw) as T;
  } catch {
    return null;
  }
}

function mapEntry(e: PredictionEntry, index: number): LockedPredictionEntryRecord {
  const p = e.prediction;
  const status = e.invalidated ? 'VOID' : e.result === StepResult.PENDING ? 'LOCKED' : 'EVALUATED';
  return {
    id: p.id,
    shoeId: p.shoeId,
    targetRoundNumber: p.targetRound,
    sequenceIndex: index,
    status,
    decision: p.decision,
    side: p.side,
    confidence: p.confidence,
    category: p.category,
    operatorAction: e.operatorAction ?? 'UNSET',
    evaluation: e.result,
    actualWinner: e.actualWinner,
    invalidated: e.invalidated,
    invalidatedByRevisionId: null,
    invalidatedAt: null,
    lockedAt: p.lockedAt,
    evaluatedAt: null,
    payloadVersion: 'SESSION-001',
    payload: JSON.stringify(p),
    createdAt: p.lockedAt,
  };
}

function mapSessionState(s: PersistedSession): SessionStateRecord {
  return {
    shoeId: s.shoeId,
    sessionVersion: s.version,
    workflow: s.workflow,
    environment: s.environment,
    currentTargetRound: null,
    paperUnitsStaked: 0,
    paperNetUnits: 0,
    paperWins: 0,
    paperLosses: 0,
    paperPushes: 0,
    createdAt: '',
    updatedAt: '',
  };
}

async function loadWebDataset(): Promise<BappDataset> {
  const history = (await readJson<WebHistoryState>(HISTORY_KEY)) ?? { shoes: [], rounds: {} };
  const shoes = history.shoes ?? [];
  const rounds: RoundRecord[] = [];
  const revisions: RevisionRecord[] = [];
  const lockedPredictions: LockedPredictionEntryRecord[] = [];
  const sessionStates: SessionStateRecord[] = [];

  for (const shoe of shoes) {
    const session = await readJson<PersistedSession>(`${SESSION_PREFIX}${shoe.id}`);
    if (session) {
      rounds.push(...session.rounds);
      revisions.push(...(session.revisions ?? []));
      session.predictions.forEach((e, i) => lockedPredictions.push(mapEntry(e, i)));
      sessionStates.push(mapSessionState(session));
    } else {
      rounds.push(...(history.rounds?.[shoe.id] ?? []));
    }
  }

  return { shoes, rounds, revisions, lockedPredictions, sessionStates };
}

export async function createDataSource(): Promise<DataSource> {
  return {
    runtime: 'web-preview',
    canWrite: false,
    loadDataset: loadWebDataset,
    applyMerge: async () => {
      throw new WriteUnavailableError();
    },
    restore: async () => {
      throw new WriteUnavailableError();
    },
  };
}
